'use strict';
/**
 * The website's demo tabs vs. what the examples ACTUALLY print — the drift guard.
 *
 * docs/index.html shows `docs/demos.js`, which is generated by running the examples for real
 * (scripts/build-site-demos.js). The page tells a visitor "this is a real run, type the command and you
 * get the same thing back". That sentence is only true while the capture matches the code — so this test
 * re-runs every demo and compares, byte for byte. Change an example, re-run the generator; forget to, and
 * this fails rather than letting the launch page quietly claim a run that no longer happens.
 *
 * It also enforces the readability rule the owner set ("focus on what a lambda human can understand
 * easily"): a demo's output must not leak internal fact/concept names or raw JSON dumps at a visitor.
 */
require('../_boot.js');
const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '../..');
const DEMOS = path.join(ROOT, 'docs', 'demos.js');

function loadDemos() {
	const src = fs.readFileSync(DEMOS, 'utf8');
	const win = {};
	// the file is `window.SG_DEMOS = [...]` — evaluate it with a window shim, no JSON reparse guesswork
	new Function('window', src)(win);
	return win.SG_DEMOS;
}

test('docs/demos.js exists and covers the groups the page renders', () => {
	assert.ok(fs.existsSync(DEMOS), 'docs/demos.js missing — run: node scripts/build-site-demos.js');
	const groups = loadDemos();
	assert.equal(groups.length, 3, 'the page renders three tab rows');
	const n = groups.reduce(( a, g ) => a + g.items.length, 0);
	assert.ok(n >= 15, 'the site should carry the full demo set (got ' + n + ')');
	for ( const g of groups ) for ( const it of g.items ) {
		assert.ok(it.id && it.title && it.blurb && it.cmd && it.out, 'demo "' + it.id + '" is complete');
		assert.match(it.cmd, /^node examples\//, 'the command shown is the one a reader would type');
	}
});

test('every captured demo output MATCHES what the example prints today (the page cannot drift)', () => {
	for ( const g of loadDemos() ) for ( const it of g.items ) {
		const parts = it.cmd.replace(/^node /, '').split(' ');
		const live = execFileSync('node', [path.join(ROOT, parts[0])].concat(parts.slice(1)),
			{ encoding: 'utf8', timeout: 120000, cwd: ROOT }).replace(/\s+$/, '');
		assert.equal(live, it.out,
			'"' + it.id + '" drifted: docs/demos.js no longer matches `' + it.cmd + '`.\n'
			+ 'Re-run: node scripts/build-site-demos.js');
	}
});

test('the demos speak PLAIN LANGUAGE — no internal names, no JSON dumps shown to a visitor', () => {
	// the owner's rule: a demo output is for someone who has never seen this repo. Internal fact names and
	// JSON belong in the CODE (with the comments around them), never in what a visitor is shown.
	const JARGON = /\b(NeedsAction|isThought|answerClass|scoreBand|critiqueVerdict|conceptSets|_etty|Ledger::|isDecision|isInquiry|readsExtra|frameStatus|cast\()/;
	for ( const g of loadDemos() ) for ( const it of g.items ) {
		if ( it.id === 'integrated' || it.id === 'head-to-head' ) continue;   // recorded transcripts: real model output, shown verbatim
		const m = it.out.match(JARGON);
		assert.equal(m, null, '"' + it.id + '" shows the internal name "' + (m && m[0]) + '" to a visitor — say it in plain words');
		assert.ok(!/^\s*\S+\s*→\s*\{"/m.test(it.out), '"' + it.id + '" dumps raw JSON at a visitor — narrate it instead');
	}
});

test('every demo ends on a plain-language sentence a reader can repeat', () => {
	for ( const g of loadDemos() ) for ( const it of g.items ) {
		if ( it.id === 'integrated' ) continue;
		const last = it.out.trim().split('\n').pop();
		assert.match(last, /(STRATEGY|BOOTSTRAP) OK — /, '"' + it.id + '" must close with its guarantee line');
		assert.ok(last.length < 160, '"' + it.id + '" closing line is too long to land (' + last.length + ' chars)');
	}
});

test('the demos SHOW the model exchange — prompts and replies, not just the machinery', () => {
	// owner, 2026-07-17: "there are no prompts/responses in the demos — it's the most important thing".
	// A page that pitches a reasoning layer for LLMs and never shows a prompt is not showing the product.
	// These are real recorded exchanges (examples/strategies/_record.js on a real Q2); this pins them there.
	const PROMPTLESS = ['f3-task-memory', 'f7-substrate', 'forge-stock', 'integrated'];   // no model by nature
	for ( const g of loadDemos() ) for ( const it of g.items ) {
		if ( PROMPTLESS.includes(it.id) ) continue;
		assert.match(it.out, /WE SENT|the "[a-z]+" step was sent/i,
			'"' + it.id + '" never shows what was sent to the model');
		assert.match(it.out, /IT REPLIED|PRODUCE L/i,
			'"' + it.id + '" never shows what the model replied');
	}
});
